import unittest
from pathlib import Path


class PhoneClientLayoutTests(unittest.TestCase):
    def test_hd_mode_requests_native_retina_detail(self):
        html = Path("phone_client/index.html").read_text(encoding="utf-8")

        self.assertIn("return ['q=85', `w=${autoFitWidth(1.25)}`, 'sharp=1'];", html)
        self.assertIn("return ['q=75', `w=${autoFitWidth(1)}`, 'sharp=1'];", html)
        self.assertIn("return ['q=50', `w=${autoFitWidth(0.75)}`, 'sharp=1'];", html)

    def test_sharp_fit_keeps_the_whole_screen_and_uses_device_pixels(self):
        html = Path("phone_client/index.html").read_text(encoding="utf-8")

        self.assertNotIn('id="btn-fit-sharp"', html)
        self.assertIn("function autoFitWidth(multiplier = 1)", html)
        self.assertIn("window.devicePixelRatio", html)
        self.assertIn("const MIN_STREAM_WIDTH = 1920;", html)
        self.assertIn("const MAX_STREAM_WIDTH = 4096;", html)
        self.assertIn("const targetPhysicalWidth = base.width * dpr * multiplier;", html)
        self.assertIn("clamp(targetPhysicalWidth, MIN_STREAM_WIDTH, MAX_STREAM_WIDTH)", html)
        self.assertIn("applyScreenTransform({ scale: 1, panX: 0, panY: 0 });", html)
        self.assertIn("autoFitResizeTimer = setTimeout", html)
        self.assertIn("screenEl.style.width = `${base.width * screenTransform.scale}px`;", html)
        self.assertIn("screenEl.style.height = `${base.height * screenTransform.scale}px`;", html)
        self.assertIn("screenEl.style.transform = `translate3d(${screenTransform.panX}px, ${screenTransform.panY}px, 0)`;", html)
        self.assertNotIn("will-change: transform;", html)
        self.assertNotIn("scale(${screenTransform.scale})", html)

    def test_viewer_uses_dynamic_offsets_and_status_dropdown(self):
        html = Path("phone_client/index.html").read_text(encoding="utf-8")

        self.assertIn("--viewer-top-offset", html)
        self.assertIn("--viewer-bottom-offset", html)
        self.assertIn('id="status-card"', html)
        self.assertIn('id="btn-status-toggle"', html)
        self.assertIn('id="toolbar"', html)
        self.assertIn("function updateViewerInsets()", html)
        self.assertIn("setStatusExpanded(", html)
        self.assertIn("for (const element of [offlineBanner])", html)
        self.assertNotIn("if (element === topbar && !statusExpanded)", html)
        self.assertIn("top: var(--viewer-top-offset);", html)
        self.assertIn("bottom: var(--viewer-bottom-offset);", html)
        self.assertNotIn("edgeTouchInsets", html)
        self.assertNotIn("TOP_EDGE_SNAP_PX", html)
        self.assertNotIn("function measureEdgeTouchInsets()", html)
        self.assertIn("const rect = screenEl.getBoundingClientRect();", html)
        self.assertIn("const width = Math.max(1, rect.width);", html)
        self.assertIn("const height = Math.max(1, rect.height);", html)
        self.assertIn("const x = (clientX - rect.left) / width;", html)
        self.assertIn("const y = (clientY - rect.top) / height;", html)
        self.assertRegex(html, r"\.topbar,\s*\.toolbar\s*\{[\s\S]*?pointer-events:\s*none;")
        self.assertRegex(html, r"\.topbar\.compact\s*\{[\s\S]*?position:\s*static;")
        self.assertRegex(html, r"\.topbar\.compact\s+\.status\s*\{[\s\S]*?position:\s*fixed;[\s\S]*?top:\s*50%;[\s\S]*?right:\s*calc\(8px \+ var\(--safe-right\)\);")
        self.assertRegex(html, r"\.status:not\(\.expanded\)\s*\{[\s\S]*?width:\s*26px;[\s\S]*?height:\s*26px;[\s\S]*?pointer-events:\s*none;")
        self.assertRegex(html, r"\.status\s*\{[\s\S]*?pointer-events:\s*auto;")
        self.assertRegex(html, r"\.tool-btn\s*\{[\s\S]*?pointer-events:\s*auto;")
        self.assertIn("topbar.classList.toggle('compact', !statusExpanded);", html)
        self.assertIn("setStatusExpanded(false);", html)
        self.assertIn("document.documentElement.style.setProperty('--viewer-top-offset'", html)
        self.assertIn("document.documentElement.style.setProperty('--viewer-bottom-offset'", html)
        self.assertIn('id="repo-prompt"', html)
        self.assertIn('id="repo-prompt-update"', html)
        self.assertIn("syncRepoState(payload", html)
        self.assertIn("runRepoUpdate()", html)
        self.assertIn("repoUpdate: apiPath('/api/repo-update')", html)
        self.assertIn("const BOOT_DEVICE_TOKEN = '{{DEVICE_TOKEN}}';", html)
        self.assertIn("deviceToken: 'ac_phone_device_token_v1'", html)
        self.assertIn("localStorage.setItem(STORAGE_KEYS.deviceToken, deviceToken);", html)
        self.assertIn("authParts.push(`token=${encodeURIComponent(TOKEN)}`);", html)
        self.assertIn("authParts.push(`device=${encodeURIComponent(deviceToken)}`);", html)
        self.assertIn("'X-AgentCockpit-Device': deviceToken", html)
        self.assertIn("function showRepoPrompt(", html)
        self.assertIn("function hideRepoPrompt(", html)
        self.assertIn("repoOfferDismissed: 'ac_phone_repo_offer_dismissed_v1'", html)
        self.assertIn("function setDismissedRepoOffer(", html)
        self.assertIn(
            "const offerSignature = nextState.updateAvailable && nextState.canUpdate && nextState.upstreamSha",
            html,
        )
        self.assertIn("rememberOffer: repoState.updateAvailable && Boolean(repoState.upstreamSha)", html)
        self.assertNotIn("!previousState.updateAvailable ||", html)
        self.assertNotIn("showRepoPrompt('Repo guncellemesi var', reason, { mode: 'update', notify: true });", html)
        self.assertIn("!repoState.updateAvailable || !repoState.canUpdate", html)
        self.assertIn("if (wasDisconnected && !isRepoPromptVisible()) {", html)
        self.assertIn("event.target.closest('#repo-prompt')", html)
        self.assertIn("[toolbar, keyboardPanel, usageHint, installSheet, wanSheet]", html)
        self.assertIn("function enqueueAction(", html)
        self.assertIn("no_screenshot: streamMode !== 'poll'", html)
        self.assertIn("scheduleNextPoll(streamMode === 'poll' ? 240 : 0);", html)
        self.assertIn("delay: isDouble ? 0.24 : 0.18", html)
        self.assertIn("function onMousePointerDown(event)", html)
        self.assertIn("function onMousePointerMove(event)", html)
        self.assertIn("function onMousePointerUp(event)", html)
        self.assertIn("function onMousePointerCancel(event)", html)
        self.assertIn("event.pointerType !== 'mouse'", html)
        self.assertIn("function onMouseContextMenu(event)", html)
        self.assertIn("function onMouseWheel(event)", html)
        self.assertIn("type: `drag_${phase}`", html)
        self.assertIn("function beginRemoteDrag(startPoint)", html)
        self.assertIn("function updateRemoteDrag(point)", html)
        self.assertIn("function finishRemoteDrag(point)", html)
        self.assertIn("screenEl.addEventListener('pointerdown', onMousePointerDown);", html)
        self.assertIn("screenEl.addEventListener('pointermove', onMousePointerMove);", html)
        self.assertIn("screenEl.addEventListener('pointerup', onMousePointerUp);", html)
        self.assertIn("screenEl.addEventListener('pointercancel', onMousePointerCancel);", html)
        self.assertIn("screenEl.addEventListener('contextmenu', onMouseContextMenu);", html)
        self.assertIn("screenEl.addEventListener('wheel', onMouseWheel, { passive: false });", html)


if __name__ == "__main__":
    unittest.main()
