from __future__ import annotations
from dataclasses import dataclass
from typing import Protocol


@dataclass(frozen=True)
class SessionRecord:
    id: str | None
    title: str
    cwd: str = ""
    source: str = ""
    last_activity: str | int | None = None


class ConversationProvider(Protocol):
    name: str

    def get_transport_mode(self) -> str: ...

    def get_profile_summary(self) -> str: ...

    def get_session_title(self) -> str | None: ...

    def get_tab(self) -> str: ...

    def set_tab(self, tab: str) -> bool: ...

    def get_cwd(self) -> str: ...

    def set_cwd(self, cwd: str) -> bool: ...

    def clear_session(self) -> None: ...

    def set_session(self, session_id: str | None, title: str | None = None) -> bool: ...

    def set_model(self, model_key: str) -> bool: ...

    def set_effort(self, effort_key: str) -> bool: ...

    def set_permission_mode(self, mode_key: str) -> bool: ...

    def set_extended_thinking(self, enabled: bool) -> bool: ...

    def sync_settings(self, focus_input: bool = False) -> tuple[bool, str]: ...

    def list_sessions(self, limit: int = 10, mode: str | None = None) -> list[SessionRecord]: ...

    def read_session_history(
        self, session_id: str | None = None, last_n: int = 10
    ) -> str: ...
